EGY_ADM2 Issue #1076
wmgeolab/geoBoundaries pull request #1077
Opened 2021-04-03 13:13 UTC by dfornatora

Correction to metadata

## Why do we need this boundary?  
 https://github.com/wmgeolab/geoBoundaries/issues/1076

## Anything Unusual?

2021-04-03 15:40 UTC, slfuhrig approved these changes

2021-04-03 15:41 UTC, slfuhrig requested changes
Please make sure canonical boundary name in meta matches ADM2 and not 1.

2021-04-05 13:46 UTC, slfuhrig approved these changes

2021-04-14 11:39 UTC, merged

2021-04-14 11:39 UTC, DanRunfola commented
Thank you!