SYR_ADM3 gbOpen
wmgeolab/geoBoundaries pull request #1220
Opened 2021-04-21 15:23 UTC by nmspage

## Why do we need this boundary?  
 #1196 

## Anything Unusual?

2021-04-21 21:50 UTC, sgmurphy216 requested changes
Hey Natalie! Great submission- one syntax error in meta.txt 'license type' field. Please correct and we'll be good to go!

2021-05-04 20:34 UTC, sgmurphy216 approved these changes

2021-05-04 20:35 UTC, sgmurphy216 commented
Great job Natalie!! Closes #1196

2021-05-06 12:57 UTC, merged

2021-05-06 12:57 UTC, DanRunfola commented
Thank you! 🇸🇾  🇸🇾