CPV_ADM2
wmgeolab/geoBoundaries pull request #1230
Opened 2021-04-22 21:38 UTC by kpupkiewicz

## Why do we need this boundary?  

#49 

## Anything Unusual?

2021-04-22 21:50 UTC, slfuhrig requested changes
Need license screenshot

2021-04-22 22:03 UTC, slfuhrig approved these changes

2021-04-22 22:04 UTC, slfuhrig commented
#49

2021-04-23 17:00 UTC, merged

2021-04-23 17:00 UTC, DanRunfola commented
Thank you!!