UKR ADM2 Issue #1190
wmgeolab/geoBoundaries pull request #1345
Opened 2021-05-24 17:41 UTC by dfornatora

## Why do we need this boundary?  
 https://github.com/wmgeolab/geoBoundaries/issues/1190

## Anything Unusual?

2021-05-25 18:00 UTC, sgmurphy216 requested changes
One small change- please replace 'UKR' in Level field with 'ADM2' and we should be good to go!

2021-05-27 18:27 UTC, sgmurphy216 requested changes
Looks like this source may be missing the region containing Kiev as well as a central northern ADM2 comprising part of the exterior border. Any other sources we can look at? 

Edit: My mistake! This is canonically correct under UKR_ADM2's organization, these areas are not represented intentionally. Thanks Dominic, this looks good.

2021-05-27 19:06 UTC, sgmurphy216 approved these changes

2021-06-02 16:29 UTC, merged

2021-06-02 16:30 UTC, DanRunfola commented
@dfornatora @sgmurphy216  Could ya'll add a note to the wiki on the northern ADMs?