gbOpen SLB_ADM0
wmgeolab/geoBoundaries pull request #1872
Opened 2021-09-30 01:34 UTC by carolinamonrivera

ISSUE #1798

## Why do we need this boundary?  
https://github.com/wmgeolab/geoBoundaries/issues/1798

## Anything Unusual?

2021-09-30 17:07 UTC, sgmurphy216 requested changes
Hey Caro! Great work here- one small change, would you mind adding the ISO 3166-2 codes for SLB_ADM1? They can be found at https://www.iso.org/obp/ui/#iso:code:3166:SB , and each ADM1 subdivision will have an ISO code associated. Thanks!

2021-11-12 21:50 UTC, sgmurphy216 approved these changes

2021-11-12 21:50 UTC, sgmurphy216 commented
Thank you Caro!!

2021-11-15 21:09 UTC, lydiatroup commented
closes #1798

2021-11-18 20:35 UTC, merged