COL_ADM2 #2032
wmgeolab/geoBoundaries pull request #2200
Opened 2022-03-25 17:16 UTC by lydiatroup

COL_ADM2 LFS Upload for Jing

2022-04-06 21:33 UTC, sgmurphy216 requested changes
Hey! Looks like this just needs a license png, then we'll be good to go

2022-04-10 20:07 UTC, lydiatroup commented
@jingjli1 please make this fix for the file and send it to me so I can reupload!

2022-04-21 03:18 UTC, lydiatroup commented
@sgmurphy216

2022-04-22 03:31 UTC, sgmurphy216 approved these changes

2022-04-28 19:07 UTC, merged