CIV_ADM3
wmgeolab/geoBoundaries pull request #978
Opened 2021-03-14 17:36 UTC by iaschreur

Issue #80

 CIV_ADM3

## Why do we need this boundary?  
 #80 

## Anything Unusual?

## Checklist:

- [ x] My submission is either a shapefile (with all the relevant files) or a geojson.
- [ x] I have included a file named "meta.txt", with all required metadata (see an example in https://bit.ly/2GtQ01i).
- [ x] I have included a file named "license.png" or "license.jpg", which includes a screenshot of the loaded website (or other source) with the licensure information.
- [ x] Everything is zipped up in a single file following the naming convention "ISO_ADMN.zip", and I am requesting it be added to the correct folder (i.e., gbOpen).

2021-03-14 19:44 UTC, slfuhrig requested changes
So close! You're failing your metadata check -- I took a quick look and noticed a typo in release type. The license type is also failing due to formatting. Take a look at the list of acceptable licenses on git and copy and paste from there so we can get an exact match for the bot. You also need to clean the attribute table in the shapefile so it includes only a "Name" and "Level" field. Check out the tutorials linked in the directory or pop into office hours for help :)

2021-04-08 21:50 UTC, slfuhrig approved these changes

2021-04-14 16:55 UTC, lydiatroup approved these changes
Looks good! Closes issue #80

2021-04-14 20:39 UTC, merged

2021-04-14 20:39 UTC, DanRunfola commented
Woo, glad to see this one get committed.  Thank you.